# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ensure_git_status_clean
    update_fastlane
  end

  desc "Run tests using fastlane"
  lane :test do
    scan(scheme: "Kwartracker")
  end

  after_all do |lane|
    reset_git_repo(skip_clean: true)
    UI.important "#{lane} Fin."
  end
end
