
# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 12 mini",
  "iPhone 12 Pro Max",
  "iPhone SE (2nd generation)"
])

languages([
  "en-US"
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
scheme("KwartrackerUITests")

# Where should the resulting screenshots be stored?
# Remove the '#' if using dark mode
# output_directory("KwartrackerUITests/screenshots/dark_mode/")
# Remove the '#' if using light mode
output_directory("KwartrackerUITests/screenshots/light_mode/")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Enabling this option will configure the Simulator to be in dark mode (false for light, true for dark)
dark_mode(false)

# Choose which project/workspace to use
# project "./Kwartracker.xcodeproj"
workspace "./Kwartracker.xcworkspace"

# For more information about all available options run
# fastlane action snapshot
